import java.text.SimpleDateFormat

plugins {
    id 'application'
}

group = 'com.reportmill'
version = new SimpleDateFormat("yyyy.MM").format(new Date())

sourceSets.main.java.srcDirs = ['src']
sourceSets.main.resources.srcDirs = ['src']

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories { mavenCentral() }

dependencies {
    implementation project(':SnapKit')
}

application {
    mainClass = 'snaptris.TetrisPane'
}
